# Generated by Django 2.0.3 on 2018-04-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='Name',
            field=models.TextField(default='Best Poll'),
            preserve_default=False,
        ),
    ]
