# Generated by Django 2.0.3 on 2018-04-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_poll_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date_closed',
            field=models.DateTimeField(default=None),
        ),
    ]
