# Generated by Django 2.0.3 on 2018-04-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20180428_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date_closed',
            field=models.DateTimeField(null=True),
        ),
    ]
